[package]
name = "solfuzz-agave"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bincode = "1.3.3"
clap = { version = "4.5.2", features = ["derive"] }
lazy_static = "1.4.0"
prost = "0.11.9"
prost-types = "0.11.9"
solana-address-lookup-table-program = { git = "https://github.com/anza-xyz/agave", rev = "b27c80a92077de291986a15a8440dfcf27f4b57c" }
solana-bpf-loader-program = { git = "https://github.com/anza-xyz/agave", rev = "b27c80a92077de291986a15a8440dfcf27f4b57c" }
solana-compute-budget-program = { git = "https://github.com/anza-xyz/agave", rev = "b27c80a92077de291986a15a8440dfcf27f4b57c" }
solana-config-program = { git = "https://github.com/anza-xyz/agave", rev = "b27c80a92077de291986a15a8440dfcf27f4b57c" }
solana-loader-v4-program = { git = "https://github.com/anza-xyz/agave", rev = "b27c80a92077de291986a15a8440dfcf27f4b57c" }
solana-program-runtime = { git = "https://github.com/anza-xyz/agave", rev = "b27c80a92077de291986a15a8440dfcf27f4b57c" }
solana-system-program = { git = "https://github.com/anza-xyz/agave", rev = "b27c80a92077de291986a15a8440dfcf27f4b57c" }
solana-sdk = { git = "https://github.com/anza-xyz/agave", rev = "b27c80a92077de291986a15a8440dfcf27f4b57c" }
thiserror = "1.0.57"

[build-dependencies]
prost-build = "0.11.9"
