[package]
name = "solfuzz-agave"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = "1.0.204"
bincode = "1.3.3"
clap = { version = "4.5.2", features = ["derive"] }
lazy_static = "1.4.0"
prost = "0.13.1"
prost-types = "0.13.1"
libc = "0.2.155"
solana-address-lookup-table-program = { git = "https://github.com/anza-xyz/agave", rev = "2c4b61e777c20379d91396340aea4f0b8d9984c1" }
solana-accounts-db = { git = "https://github.com/anza-xyz/agave", rev = "2c4b61e777c20379d91396340aea4f0b8d9984c1" }
solana-bpf-loader-program = { git = "https://github.com/anza-xyz/agave", rev = "2c4b61e777c20379d91396340aea4f0b8d9984c1" }
solana-compute-budget = { git = "https://github.com/anza-xyz/agave", rev = "2c4b61e777c20379d91396340aea4f0b8d9984c1" }
solana-compute-budget-program = { git = "https://github.com/anza-xyz/agave", rev = "2c4b61e777c20379d91396340aea4f0b8d9984c1" }
solana-config-program = { git = "https://github.com/anza-xyz/agave", rev = "2c4b61e777c20379d91396340aea4f0b8d9984c1" }
solana-loader-v4-program = { git = "https://github.com/anza-xyz/agave", rev = "2c4b61e777c20379d91396340aea4f0b8d9984c1" }
solana-log-collector = { git = "https://github.com/anza-xyz/agave", rev = "2c4b61e777c20379d91396340aea4f0b8d9984c1" }
solana-program = { git = "https://github.com/anza-xyz/agave", rev = "2c4b61e777c20379d91396340aea4f0b8d9984c1" }
solana-program-runtime = { git = "https://github.com/anza-xyz/agave", rev = "2c4b61e777c20379d91396340aea4f0b8d9984c1" }
solana-runtime = { git = "https://github.com/anza-xyz/agave", rev = "2c4b61e777c20379d91396340aea4f0b8d9984c1", features = ["dev-context-only-utils"] }
solana-stake-program = { git = "https://github.com/anza-xyz/agave", rev = "2c4b61e777c20379d91396340aea4f0b8d9984c1" }
solana-system-program = { git = "https://github.com/anza-xyz/agave", rev = "2c4b61e777c20379d91396340aea4f0b8d9984c1" }
solana-svm = { git = "https://github.com/anza-xyz/agave", rev = "2c4b61e777c20379d91396340aea4f0b8d9984c1" }
solana-sdk = { git = "https://github.com/anza-xyz/agave", rev = "2c4b61e777c20379d91396340aea4f0b8d9984c1" }
solana-timings = { git = "https://github.com/anza-xyz/agave", rev = "2c4b61e777c20379d91396340aea4f0b8d9984c1" }
solana-vote-program = { git = "https://github.com/anza-xyz/agave", rev = "2c4b61e777c20379d91396340aea4f0b8d9984c1" }
solana-zk-sdk = { git = "https://github.com/anza-xyz/agave", rev = "2c4b61e777c20379d91396340aea4f0b8d9984c1" }
solana-zk-elgamal-proof-program = { git = "https://github.com/anza-xyz/agave", rev = "2c4b61e777c20379d91396340aea4f0b8d9984c1" }
solfuzz-agave-macro = { path = "macro" }
thiserror = "1.0.61"
log = "0.4.22" # without this, prost 0.11-0.13 complain

[build-dependencies]
prost-build = "0.13.1"


[patch.crates-io]
solana-program = { git = "https://github.com/anza-xyz/agave", rev = "2c4b61e777c20379d91396340aea4f0b8d9984c1" }
solana-zk-token-sdk = { git = "https://github.com/anza-xyz/agave", rev = "2c4b61e777c20379d91396340aea4f0b8d9984c1" }
