[package]
name = "solfuzz-agave"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
bincode = "1.3.3"
lazy_static = "1.4.0"
prost = "0.11.9"
prost-types = "0.11.9"
solana-address-lookup-table-program = { git = "https://github.com/ripatel-fd/solana", branch = "patch-1" }
solana-bpf-loader-program = { git = "https://github.com/ripatel-fd/solana", branch = "patch-1" }
solana-compute-budget-program = { git = "https://github.com/ripatel-fd/solana", branch = "patch-1" }
solana-config-program = { git = "https://github.com/ripatel-fd/solana", branch = "patch-1" }
solana-loader-v4-program = { git = "https://github.com/ripatel-fd/solana", branch = "patch-1" }
solana-program-runtime = { git = "https://github.com/ripatel-fd/solana", branch = "patch-1" }
solana-system-program = { git = "https://github.com/ripatel-fd/solana", branch = "patch-1" }
solana-sdk = { git = "https://github.com/ripatel-fd/solana", branch = "patch-1" }
thiserror = "1.0.57"

[build-dependencies]
prost-build = "0.11.9"

[patch."https://github.com/anza-xyz/agave"]
solana-program = { git = "https://github.com/ripatel-fd/solana", branch = "patch-1" }
