[package]
name = "solfuzz-agave"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bincode = "1.3.3"
clap = { version = "4.5.2", features = ["derive"] }
lazy_static = "1.4.0"
prost = "0.11.9"
prost-types = "0.11.9"
solana-address-lookup-table-program = "1.18.9"
solana-bpf-loader-program = "1.18.9"
solana-compute-budget-program = "1.18.9"
solana-config-program = "1.18.9"
solana-loader-v4-program = "1.18.9"
solana-program-runtime = "1.18.9"
solana-system-program = "1.18.9"
solana-sdk = "1.18.9"
thiserror = "1.0.56"

[build-dependencies]
prost-build = "0.11.9"
